### PR TITLE
 kuhai's better s2 setup

### PR DESCRIPTION
**Pull request by Ladish**
with stellar show and c1+fs during s2
1572 dps

### CODE REVIEW

**Comment by b1ueb1ues** [comment]
need to measure c1+fs frame

**Comment by b1ueb1ues** [comment]
OMG, there is a big bug in wiki's data, fs_alt only deal 2 hits to dragon trial 1 hit to little creep instead of 3 hits

**Comment by Ladish** [comment]
shouldn't that hits 3 times anyway? I always see 3 lines of damage in raid

**Comment by b1ueb1ues** [comment]
No problem in raid that always do 3 hits fs, but can't always do 3 hits fs to smaller target, I just notice that.

**Comment by Ladish** [comment]
you're right, I think it might be bugged rn

**Pull request merged**
